/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AssetType = IDL.Variant({
  'Stock' : IDL.Null,
  'Crypto' : IDL.Null,
});
export const AssetHolding = IDL.Record({
  'name' : IDL.Text,
  'yieldRate' : IDL.Float64,
  'stakedQty' : IDL.Float64,
  'quantity' : IDL.Float64,
  'assetType' : AssetType,
  'symbol' : IDL.Text,
});
export const Time = IDL.Int;
export const PriceData = IDL.Record({
  'isMockData' : IDL.Bool,
  'lastUpdated' : Time,
  'isLive' : IDL.Bool,
  'priceNOK' : IDL.Float64,
  'priceUSD' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const PortfolioSnapshot = IDL.Record({
  'totalValueNOK' : IDL.Float64,
  'date' : IDL.Text,
  'recordedAt' : Time,
  'perAssetValues' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const AssetWithPrice = IDL.Record({
  'holding' : AssetHolding,
  'price' : IDL.Opt(PriceData),
  'valueNOK' : IDL.Float64,
});
export const PortfolioSummary = IDL.Record({
  'totalValueNOK' : IDL.Float64,
  'assets' : IDL.Vec(AssetWithPrice),
  'lastPriceUpdate' : IDL.Opt(Time),
  'hasLiveData' : IDL.Bool,
  'usdNokRate' : IDL.Float64,
});
export const YieldInfo = IDL.Record({
  'annualYieldRate' : IDL.Float64,
  'yearlyYieldNOK' : IDL.Float64,
  'monthlyYieldAsset' : IDL.Float64,
  'monthlyYieldNOK' : IDL.Float64,
  'yearlyYieldAsset' : IDL.Float64,
  'stakedQty' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addAsset' : IDL.Func([AssetHolding], [], []),
  'clearAllSnapshots' : IDL.Func([], [], []),
  'deleteAsset' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAsset' : IDL.Func([IDL.Text], [IDL.Opt(AssetHolding)], []),
  'getCurrentPrices' : IDL.Func([], [IDL.Vec(PriceData)], []),
  'getHistoricalSnapshots' : IDL.Func([], [IDL.Vec(PortfolioSnapshot)], []),
  'getLastNSnapshots' : IDL.Func([IDL.Nat], [IDL.Vec(PortfolioSnapshot)], []),
  'getPortfolio' : IDL.Func([], [IDL.Vec(AssetHolding)], []),
  'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], []),
  'getYieldInfo' : IDL.Func([], [IDL.Vec(YieldInfo)], []),
  'recordDailySnapshot' : IDL.Func([], [IDL.Bool], []),
  'refreshPrices' : IDL.Func([], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAsset' : IDL.Func([AssetHolding], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AssetType = IDL.Variant({ 'Stock' : IDL.Null, 'Crypto' : IDL.Null });
  const AssetHolding = IDL.Record({
    'name' : IDL.Text,
    'yieldRate' : IDL.Float64,
    'stakedQty' : IDL.Float64,
    'quantity' : IDL.Float64,
    'assetType' : AssetType,
    'symbol' : IDL.Text,
  });
  const Time = IDL.Int;
  const PriceData = IDL.Record({
    'isMockData' : IDL.Bool,
    'lastUpdated' : Time,
    'isLive' : IDL.Bool,
    'priceNOK' : IDL.Float64,
    'priceUSD' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const PortfolioSnapshot = IDL.Record({
    'totalValueNOK' : IDL.Float64,
    'date' : IDL.Text,
    'recordedAt' : Time,
    'perAssetValues' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const AssetWithPrice = IDL.Record({
    'holding' : AssetHolding,
    'price' : IDL.Opt(PriceData),
    'valueNOK' : IDL.Float64,
  });
  const PortfolioSummary = IDL.Record({
    'totalValueNOK' : IDL.Float64,
    'assets' : IDL.Vec(AssetWithPrice),
    'lastPriceUpdate' : IDL.Opt(Time),
    'hasLiveData' : IDL.Bool,
    'usdNokRate' : IDL.Float64,
  });
  const YieldInfo = IDL.Record({
    'annualYieldRate' : IDL.Float64,
    'yearlyYieldNOK' : IDL.Float64,
    'monthlyYieldAsset' : IDL.Float64,
    'monthlyYieldNOK' : IDL.Float64,
    'yearlyYieldAsset' : IDL.Float64,
    'stakedQty' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addAsset' : IDL.Func([AssetHolding], [], []),
    'clearAllSnapshots' : IDL.Func([], [], []),
    'deleteAsset' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAsset' : IDL.Func([IDL.Text], [IDL.Opt(AssetHolding)], []),
    'getCurrentPrices' : IDL.Func([], [IDL.Vec(PriceData)], []),
    'getHistoricalSnapshots' : IDL.Func([], [IDL.Vec(PortfolioSnapshot)], []),
    'getLastNSnapshots' : IDL.Func([IDL.Nat], [IDL.Vec(PortfolioSnapshot)], []),
    'getPortfolio' : IDL.Func([], [IDL.Vec(AssetHolding)], []),
    'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], []),
    'getYieldInfo' : IDL.Func([], [IDL.Vec(YieldInfo)], []),
    'recordDailySnapshot' : IDL.Func([], [IDL.Bool], []),
    'refreshPrices' : IDL.Func([], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAsset' : IDL.Func([AssetHolding], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };