/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssetHolding {
  'name' : string,
  'yieldRate' : number,
  'stakedQty' : number,
  'quantity' : number,
  'assetType' : AssetType,
  'symbol' : string,
}
export type AssetType = { 'Stock' : null } |
  { 'Crypto' : null };
export interface AssetWithPrice {
  'holding' : AssetHolding,
  'price' : [] | [PriceData],
  'valueNOK' : number,
}
export interface PortfolioSnapshot {
  'totalValueNOK' : number,
  'date' : string,
  'recordedAt' : Time,
  'perAssetValues' : Array<[string, number]>,
}
export interface PortfolioSummary {
  'totalValueNOK' : number,
  'assets' : Array<AssetWithPrice>,
  'lastPriceUpdate' : [] | [Time],
  'hasLiveData' : boolean,
  'usdNokRate' : number,
}
export interface PriceData {
  'isMockData' : boolean,
  'lastUpdated' : Time,
  'isLive' : boolean,
  'priceNOK' : number,
  'priceUSD' : number,
  'symbol' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface YieldInfo {
  'annualYieldRate' : number,
  'yearlyYieldNOK' : number,
  'monthlyYieldAsset' : number,
  'monthlyYieldNOK' : number,
  'yearlyYieldAsset' : number,
  'stakedQty' : number,
  'symbol' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addAsset' : ActorMethod<[AssetHolding], undefined>,
  'clearAllSnapshots' : ActorMethod<[], undefined>,
  'deleteAsset' : ActorMethod<[string], boolean>,
  'getAsset' : ActorMethod<[string], [] | [AssetHolding]>,
  'getCurrentPrices' : ActorMethod<[], Array<PriceData>>,
  'getHistoricalSnapshots' : ActorMethod<[], Array<PortfolioSnapshot>>,
  'getLastNSnapshots' : ActorMethod<[bigint], Array<PortfolioSnapshot>>,
  'getPortfolio' : ActorMethod<[], Array<AssetHolding>>,
  'getPortfolioSummary' : ActorMethod<[], PortfolioSummary>,
  'getYieldInfo' : ActorMethod<[], Array<YieldInfo>>,
  'recordDailySnapshot' : ActorMethod<[], boolean>,
  'refreshPrices' : ActorMethod<[], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAsset' : ActorMethod<[AssetHolding], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];