/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PriceData {
    isMockData: boolean;
    lastUpdated: Time;
    isLive: boolean;
    priceNOK: number;
    priceUSD: number;
    symbol: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface YieldInfo {
    annualYieldRate: number;
    yearlyYieldNOK: number;
    monthlyYieldAsset: number;
    monthlyYieldNOK: number;
    yearlyYieldAsset: number;
    stakedQty: number;
    symbol: string;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PortfolioSummary {
    totalValueNOK: number;
    assets: Array<AssetWithPrice>;
    lastPriceUpdate?: Time;
    hasLiveData: boolean;
    usdNokRate: number;
}
export interface PortfolioSnapshot {
    totalValueNOK: number;
    date: string;
    recordedAt: Time;
    perAssetValues: Array<[string, number]>;
}
export interface AssetWithPrice {
    holding: AssetHolding;
    price?: PriceData;
    valueNOK: number;
}
export interface AssetHolding {
    name: string;
    yieldRate: number;
    stakedQty: number;
    quantity: number;
    assetType: AssetType;
    symbol: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum AssetType {
    Stock = "Stock",
    Crypto = "Crypto"
}
export interface backendInterface {
    addAsset(holding: AssetHolding): Promise<void>;
    clearAllSnapshots(): Promise<void>;
    deleteAsset(symbol: string): Promise<boolean>;
    getAsset(symbol: string): Promise<AssetHolding | null>;
    getCurrentPrices(): Promise<Array<PriceData>>;
    getHistoricalSnapshots(): Promise<Array<PortfolioSnapshot>>;
    getLastNSnapshots(n: bigint): Promise<Array<PortfolioSnapshot>>;
    getPortfolio(): Promise<Array<AssetHolding>>;
    getPortfolioSummary(): Promise<PortfolioSummary>;
    getYieldInfo(): Promise<Array<YieldInfo>>;
    recordDailySnapshot(): Promise<boolean>;
    refreshPrices(): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAsset(holding: AssetHolding): Promise<boolean>;
}
import type { AssetHolding as _AssetHolding, AssetType as _AssetType, AssetWithPrice as _AssetWithPrice, PortfolioSummary as _PortfolioSummary, PriceData as _PriceData, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAsset(arg0: AssetHolding): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAsset(to_candid_AssetHolding_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAsset(to_candid_AssetHolding_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async clearAllSnapshots(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllSnapshots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllSnapshots();
            return result;
        }
    }
    async deleteAsset(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAsset(arg0);
            return result;
        }
    }
    async getAsset(arg0: string): Promise<AssetHolding | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAsset(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAsset(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentPrices(): Promise<Array<PriceData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentPrices();
            return result;
        }
    }
    async getHistoricalSnapshots(): Promise<Array<PortfolioSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoricalSnapshots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoricalSnapshots();
            return result;
        }
    }
    async getLastNSnapshots(arg0: bigint): Promise<Array<PortfolioSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastNSnapshots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastNSnapshots(arg0);
            return result;
        }
    }
    async getPortfolio(): Promise<Array<AssetHolding>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolio();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolio();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioSummary(): Promise<PortfolioSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSummary();
                return from_candid_PortfolioSummary_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSummary();
            return from_candid_PortfolioSummary_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getYieldInfo(): Promise<Array<YieldInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getYieldInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getYieldInfo();
            return result;
        }
    }
    async recordDailySnapshot(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDailySnapshot();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDailySnapshot();
            return result;
        }
    }
    async refreshPrices(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshPrices();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAsset(arg0: AssetHolding): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAsset(to_candid_AssetHolding_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAsset(to_candid_AssetHolding_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AssetHolding_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetHolding): AssetHolding {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_AssetType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetType): AssetType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_AssetWithPrice_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetWithPrice): AssetWithPrice {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioSummary_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioSummary): PortfolioSummary {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PriceData]): PriceData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AssetHolding]): AssetHolding | null {
    return value.length === 0 ? null : from_candid_AssetHolding_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalValueNOK: number;
    assets: Array<_AssetWithPrice>;
    lastPriceUpdate: [] | [_Time];
    hasLiveData: boolean;
    usdNokRate: number;
}): {
    totalValueNOK: number;
    assets: Array<AssetWithPrice>;
    lastPriceUpdate?: Time;
    hasLiveData: boolean;
    usdNokRate: number;
} {
    return {
        totalValueNOK: value.totalValueNOK,
        assets: from_candid_vec_n13(_uploadFile, _downloadFile, value.assets),
        lastPriceUpdate: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.lastPriceUpdate)),
        hasLiveData: value.hasLiveData,
        usdNokRate: value.usdNokRate
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    holding: _AssetHolding;
    price: [] | [_PriceData];
    valueNOK: number;
}): {
    holding: AssetHolding;
    price?: PriceData;
    valueNOK: number;
} {
    return {
        holding: from_candid_AssetHolding_n6(_uploadFile, _downloadFile, value.holding),
        price: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.price)),
        valueNOK: value.valueNOK
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    yieldRate: number;
    stakedQty: number;
    quantity: number;
    assetType: _AssetType;
    symbol: string;
}): {
    name: string;
    yieldRate: number;
    stakedQty: number;
    quantity: number;
    assetType: AssetType;
    symbol: string;
} {
    return {
        name: value.name,
        yieldRate: value.yieldRate,
        stakedQty: value.stakedQty,
        quantity: value.quantity,
        assetType: from_candid_AssetType_n8(_uploadFile, _downloadFile, value.assetType),
        symbol: value.symbol
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Stock: null;
} | {
    Crypto: null;
}): AssetType {
    return "Stock" in value ? AssetType.Stock : "Crypto" in value ? AssetType.Crypto : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssetHolding>): Array<AssetHolding> {
    return value.map((x)=>from_candid_AssetHolding_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssetWithPrice>): Array<AssetWithPrice> {
    return value.map((x)=>from_candid_AssetWithPrice_n14(_uploadFile, _downloadFile, x));
}
function to_candid_AssetHolding_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetHolding): _AssetHolding {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_AssetType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): _AssetType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    yieldRate: number;
    stakedQty: number;
    quantity: number;
    assetType: AssetType;
    symbol: string;
}): {
    name: string;
    yieldRate: number;
    stakedQty: number;
    quantity: number;
    assetType: _AssetType;
    symbol: string;
} {
    return {
        name: value.name,
        yieldRate: value.yieldRate,
        stakedQty: value.stakedQty,
        quantity: value.quantity,
        assetType: to_candid_AssetType_n3(_uploadFile, _downloadFile, value.assetType),
        symbol: value.symbol
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): {
    Stock: null;
} | {
    Crypto: null;
} {
    return value == AssetType.Stock ? {
        Stock: null
    } : value == AssetType.Crypto ? {
        Crypto: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
